### ISSUE TITLE
linux+python2 error

### ISSUE THREAD

**Issue by diablov** [hellman/libnum#12]
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import libnum
>>> libnum.s2n("abcd")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/libnum/strings.py", line 10, in s2n
    return int(s.encode("utf-8").hex(), 16)
AttributeError: 'str' object has no attribute 'hex'

**Comment by adfnekc** [comment]
yeah,i have same probelem

**Comment by hellman** [comment]
the code has changed now, please check
