### ISSUE TITLE
Cannot be installed from a relative path

### ISSUE THREAD

**Issue by Reelix** [hellman/libnum#7]
> python libnum\setup.py install

Fails

```
running install
running build
running build_py
package init file 'libnum\__init__.py' not found (or not a regular file)
creating build
creating build\lib
creating build\lib\libnum
copying libnum\setup.py -> build\lib\libnum
error: package directory 'libnum\chains' does not exist
```

Going to the directory itself then running

> python setup.py install

Succeeds

**Comment by JafarAkhondali** [comment]
@Reelix See
https://github.com/JafarAkhondali/python3-libnum

**Comment by hellman** [comment]
switched building to poetry (for development), otherwise can be installed from pip
