### ISSUE TITLE
Support for python 3

### ISSUE THREAD

**Issue by mzfr** [hellman/libnum#9]
Will you be adding support for Python 3 in this?

**Comment by JafarAkhondali** [comment]
@mzfr This project looks inactive, I've forked it to support for python3:
https://github.com/JafarAkhondali/python3-libnum   

`pip install libnum`

**Comment by hellman** [comment]
Sorry, I somehow wasn't watching this repo. I accepted the PR

**Comment by JafarAkhondali** [comment]
@hellman Please contact me if you want to manage the `libnum` on pypi.org.
jafar.akhoondali@gmail.com
